var WMS130_Module_Factory = function () {
  var WMS130 = {
    name: 'WMS130',
    defaultElementNamespaceURI: 'http:\/\/www.opengis.net\/wms',
    typeInfos: [{
        localName: 'ContactAddress',
        typeName: null,
        propertyInfos: [{
            name: 'addressType',
            elementName: 'AddressType'
          }, {
            name: 'address',
            elementName: 'Address'
          }, {
            name: 'city',
            elementName: 'City'
          }, {
            name: 'stateOrProvince',
            elementName: 'StateOrProvince'
          }, {
            name: 'postCode',
            elementName: 'PostCode'
          }, {
            name: 'country',
            elementName: 'Country'
          }]
      }, {
        localName: 'DataURL',
        typeName: null,
        propertyInfos: [{
            name: 'format',
            elementName: 'Format'
          }, {
            name: 'onlineResource',
            elementName: 'OnlineResource',
            typeInfo: '.OnlineResource'
          }]
      }, {
        localName: 'WMSCapabilities',
        typeName: null,
        propertyInfos: [{
            name: 'service',
            elementName: 'Service',
            typeInfo: '.Service'
          }, {
            name: 'capability',
            elementName: 'Capability',
            typeInfo: '.Capability'
          }, {
            name: 'version',
            attributeName: {
              localPart: 'version'
            },
            type: 'attribute'
          }, {
            name: 'updateSequence',
            attributeName: {
              localPart: 'updateSequence'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'MetadataURL',
        typeName: null,
        propertyInfos: [{
            name: 'format',
            elementName: 'Format'
          }, {
            name: 'onlineResource',
            elementName: 'OnlineResource',
            typeInfo: '.OnlineResource'
          }, {
            name: 'type',
            attributeName: {
              localPart: 'type'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'LogoURL',
        typeName: null,
        propertyInfos: [{
            name: 'format',
            elementName: 'Format'
          }, {
            name: 'onlineResource',
            elementName: 'OnlineResource',
            typeInfo: '.OnlineResource'
          }, {
            name: 'width',
            typeInfo: 'Integer',
            attributeName: {
              localPart: 'width'
            },
            type: 'attribute'
          }, {
            name: 'height',
            typeInfo: 'Integer',
            attributeName: {
              localPart: 'height'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'EXGeographicBoundingBox',
        typeName: null,
        propertyInfos: [{
            name: 'westBoundLongitude',
            typeInfo: 'Double'
          }, {
            name: 'eastBoundLongitude',
            typeInfo: 'Double'
          }, {
            name: 'southBoundLatitude',
            typeInfo: 'Double'
          }, {
            name: 'northBoundLatitude',
            typeInfo: 'Double'
          }]
      }, {
        localName: 'StyleSheetURL',
        typeName: null,
        propertyInfos: [{
            name: 'format',
            elementName: 'Format'
          }, {
            name: 'onlineResource',
            elementName: 'OnlineResource',
            typeInfo: '.OnlineResource'
          }]
      }, {
        localName: 'Dimension',
        typeName: null,
        propertyInfos: [{
            name: 'value',
            type: 'value'
          }, {
            name: 'name',
            attributeName: {
              localPart: 'name'
            },
            type: 'attribute'
          }, {
            name: 'units',
            attributeName: {
              localPart: 'units'
            },
            type: 'attribute'
          }, {
            name: 'unitSymbol',
            attributeName: {
              localPart: 'unitSymbol'
            },
            type: 'attribute'
          }, {
            name: '_default',
            attributeName: {
              localPart: 'default'
            },
            type: 'attribute'
          }, {
            name: 'multipleValues',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'multipleValues'
            },
            type: 'attribute'
          }, {
            name: 'nearestValue',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'nearestValue'
            },
            type: 'attribute'
          }, {
            name: 'current',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'current'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'Post',
        typeName: null,
        propertyInfos: [{
            name: 'onlineResource',
            elementName: 'OnlineResource',
            typeInfo: '.OnlineResource'
          }]
      }, {
        localName: 'BoundingBox',
        typeName: null,
        propertyInfos: [{
            name: 'crs',
            attributeName: {
              localPart: 'CRS'
            },
            type: 'attribute'
          }, {
            name: 'minx',
            typeInfo: 'Double',
            attributeName: {
              localPart: 'minx'
            },
            type: 'attribute'
          }, {
            name: 'miny',
            typeInfo: 'Double',
            attributeName: {
              localPart: 'miny'
            },
            type: 'attribute'
          }, {
            name: 'maxx',
            typeInfo: 'Double',
            attributeName: {
              localPart: 'maxx'
            },
            type: 'attribute'
          }, {
            name: 'maxy',
            typeInfo: 'Double',
            attributeName: {
              localPart: 'maxy'
            },
            type: 'attribute'
          }, {
            name: 'resx',
            typeInfo: 'Double',
            attributeName: {
              localPart: 'resx'
            },
            type: 'attribute'
          }, {
            name: 'resy',
            typeInfo: 'Double',
            attributeName: {
              localPart: 'resy'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'Service',
        typeName: null,
        propertyInfos: [{
            name: 'name',
            elementName: 'Name'
          }, {
            name: 'title',
            elementName: 'Title'
          }, {
            name: '_abstract',
            elementName: 'Abstract'
          }, {
            name: 'keywordList',
            elementName: 'KeywordList',
            typeInfo: '.KeywordList'
          }, {
            name: 'onlineResource',
            elementName: 'OnlineResource',
            typeInfo: '.OnlineResource'
          }, {
            name: 'contactInformation',
            elementName: 'ContactInformation',
            typeInfo: '.ContactInformation'
          }, {
            name: 'fees',
            elementName: 'Fees'
          }, {
            name: 'accessConstraints',
            elementName: 'AccessConstraints'
          }, {
            name: 'layerLimit',
            elementName: 'LayerLimit',
            typeInfo: 'Integer'
          }, {
            name: 'maxWidth',
            elementName: 'MaxWidth',
            typeInfo: 'Integer'
          }, {
            name: 'maxHeight',
            elementName: 'MaxHeight',
            typeInfo: 'Integer'
          }]
      }, {
        localName: 'ContactInformation',
        typeName: null,
        propertyInfos: [{
            name: 'contactPersonPrimary',
            elementName: 'ContactPersonPrimary',
            typeInfo: '.ContactPersonPrimary'
          }, {
            name: 'contactPosition',
            elementName: 'ContactPosition'
          }, {
            name: 'contactAddress',
            elementName: 'ContactAddress',
            typeInfo: '.ContactAddress'
          }, {
            name: 'contactVoiceTelephone',
            elementName: 'ContactVoiceTelephone'
          }, {
            name: 'contactFacsimileTelephone',
            elementName: 'ContactFacsimileTelephone'
          }, {
            name: 'contactElectronicMailAddress',
            elementName: 'ContactElectronicMailAddress'
          }]
      }, {
        localName: 'OperationType',
        propertyInfos: [{
            name: 'format',
            collection: true,
            elementName: 'Format'
          }, {
            name: 'dcpType',
            collection: true,
            elementName: 'DCPType',
            typeInfo: '.DCPType'
          }]
      }, {
        localName: 'OnlineResource',
        typeName: null,
        propertyInfos: [{
            name: 'type',
            attributeName: {
              localPart: 'type',
              namespaceURI: 'http:\/\/www.w3.org\/1999\/xlink'
            },
            type: 'attribute'
          }, {
            name: 'href',
            attributeName: {
              localPart: 'href',
              namespaceURI: 'http:\/\/www.w3.org\/1999\/xlink'
            },
            type: 'attribute'
          }, {
            name: 'role',
            attributeName: {
              localPart: 'role',
              namespaceURI: 'http:\/\/www.w3.org\/1999\/xlink'
            },
            type: 'attribute'
          }, {
            name: 'arcrole',
            attributeName: {
              localPart: 'arcrole',
              namespaceURI: 'http:\/\/www.w3.org\/1999\/xlink'
            },
            type: 'attribute'
          }, {
            name: 'title',
            attributeName: {
              localPart: 'title',
              namespaceURI: 'http:\/\/www.w3.org\/1999\/xlink'
            },
            type: 'attribute'
          }, {
            name: 'show',
            attributeName: {
              localPart: 'show',
              namespaceURI: 'http:\/\/www.w3.org\/1999\/xlink'
            },
            type: 'attribute'
          }, {
            name: 'actuate',
            attributeName: {
              localPart: 'actuate',
              namespaceURI: 'http:\/\/www.w3.org\/1999\/xlink'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'DCPType',
        typeName: null,
        propertyInfos: [{
            name: 'http',
            elementName: 'HTTP',
            typeInfo: '.HTTP'
          }]
      }, {
        localName: 'FeatureListURL',
        typeName: null,
        propertyInfos: [{
            name: 'format',
            elementName: 'Format'
          }, {
            name: 'onlineResource',
            elementName: 'OnlineResource',
            typeInfo: '.OnlineResource'
          }]
      }, {
        localName: 'Capability',
        typeName: null,
        propertyInfos: [{
            name: 'request',
            elementName: 'Request',
            typeInfo: '.Request'
          }, {
            name: 'exception',
            elementName: 'Exception',
            typeInfo: '.Exception'
          }, {
            name: 'extendedCapabilities',
            collection: true,
            elementName: '_ExtendedCapabilities',
            typeInfo: 'AnyType'
          }, {
            name: 'layer',
            elementName: 'Layer',
            typeInfo: '.Layer'
          }]
      }, {
        localName: 'HTTP',
        typeName: null,
        propertyInfos: [{
            name: 'get',
            elementName: 'Get',
            typeInfo: '.Get'
          }, {
            name: 'post',
            elementName: 'Post',
            typeInfo: '.Post'
          }]
      }, {
        localName: 'Style',
        typeName: null,
        propertyInfos: [{
            name: 'name',
            elementName: 'Name'
          }, {
            name: 'title',
            elementName: 'Title'
          }, {
            name: '_abstract',
            elementName: 'Abstract'
          }, {
            name: 'legendURL',
            collection: true,
            elementName: 'LegendURL',
            typeInfo: '.LegendURL'
          }, {
            name: 'styleSheetURL',
            elementName: 'StyleSheetURL',
            typeInfo: '.StyleSheetURL'
          }, {
            name: 'styleURL',
            elementName: 'StyleURL',
            typeInfo: '.StyleURL'
          }]
      }, {
        localName: 'Request',
        typeName: null,
        propertyInfos: [{
            name: 'getCapabilities',
            elementName: 'GetCapabilities',
            typeInfo: '.OperationType'
          }, {
            name: 'getMap',
            elementName: 'GetMap',
            typeInfo: '.OperationType'
          }, {
            name: 'getFeatureInfo',
            elementName: 'GetFeatureInfo',
            typeInfo: '.OperationType'
          }, {
            name: 'extendedOperation',
            collection: true,
            elementName: '_ExtendedOperation',
            typeInfo: '.OperationType'
          }]
      }, {
        localName: 'StyleURL',
        typeName: null,
        propertyInfos: [{
            name: 'format',
            elementName: 'Format'
          }, {
            name: 'onlineResource',
            elementName: 'OnlineResource',
            typeInfo: '.OnlineResource'
          }]
      }, {
        localName: 'Layer',
        typeName: null,
        propertyInfos: [{
            name: 'name',
            elementName: 'Name'
          }, {
            name: 'title',
            elementName: 'Title'
          }, {
            name: '_abstract',
            elementName: 'Abstract'
          }, {
            name: 'keywordList',
            elementName: 'KeywordList',
            typeInfo: '.KeywordList'
          }, {
            name: 'crs',
            collection: true,
            elementName: 'CRS'
          }, {
            name: 'exGeographicBoundingBox',
            elementName: 'EX_GeographicBoundingBox',
            typeInfo: '.EXGeographicBoundingBox'
          }, {
            name: 'boundingBox',
            collection: true,
            elementName: 'BoundingBox',
            typeInfo: '.BoundingBox'
          }, {
            name: 'dimension',
            collection: true,
            elementName: 'Dimension',
            typeInfo: '.Dimension'
          }, {
            name: 'attribution',
            elementName: 'Attribution',
            typeInfo: '.Attribution'
          }, {
            name: 'authorityURL',
            collection: true,
            elementName: 'AuthorityURL',
            typeInfo: '.AuthorityURL'
          }, {
            name: 'identifier',
            collection: true,
            elementName: 'Identifier',
            typeInfo: '.Identifier'
          }, {
            name: 'metadataURL',
            collection: true,
            elementName: 'MetadataURL',
            typeInfo: '.MetadataURL'
          }, {
            name: 'dataURL',
            collection: true,
            elementName: 'DataURL',
            typeInfo: '.DataURL'
          }, {
            name: 'featureListURL',
            collection: true,
            elementName: 'FeatureListURL',
            typeInfo: '.FeatureListURL'
          }, {
            name: 'style',
            collection: true,
            elementName: 'Style',
            typeInfo: '.Style'
          }, {
            name: 'minScaleDenominator',
            elementName: 'MinScaleDenominator',
            typeInfo: 'Double'
          }, {
            name: 'maxScaleDenominator',
            elementName: 'MaxScaleDenominator',
            typeInfo: 'Double'
          }, {
            name: 'layer',
            collection: true,
            elementName: 'Layer',
            typeInfo: '.Layer'
          }, {
            name: 'queryable',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'queryable'
            },
            type: 'attribute'
          }, {
            name: 'cascaded',
            typeInfo: 'Integer',
            attributeName: {
              localPart: 'cascaded'
            },
            type: 'attribute'
          }, {
            name: 'opaque',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'opaque'
            },
            type: 'attribute'
          }, {
            name: 'noSubsets',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'noSubsets'
            },
            type: 'attribute'
          }, {
            name: 'fixedWidth',
            typeInfo: 'Integer',
            attributeName: {
              localPart: 'fixedWidth'
            },
            type: 'attribute'
          }, {
            name: 'fixedHeight',
            typeInfo: 'Integer',
            attributeName: {
              localPart: 'fixedHeight'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'KeywordList',
        typeName: null,
        propertyInfos: [{
            name: 'keyword',
            collection: true,
            elementName: 'Keyword',
            typeInfo: '.Keyword'
          }]
      }, {
        localName: 'Get',
        typeName: null,
        propertyInfos: [{
            name: 'onlineResource',
            elementName: 'OnlineResource',
            typeInfo: '.OnlineResource'
          }]
      }, {
        localName: 'Attribution',
        typeName: null,
        propertyInfos: [{
            name: 'title',
            elementName: 'Title'
          }, {
            name: 'onlineResource',
            elementName: 'OnlineResource',
            typeInfo: '.OnlineResource'
          }, {
            name: 'logoURL',
            elementName: 'LogoURL',
            typeInfo: '.LogoURL'
          }]
      }, {
        localName: 'AuthorityURL',
        typeName: null,
        propertyInfos: [{
            name: 'onlineResource',
            elementName: 'OnlineResource',
            typeInfo: '.OnlineResource'
          }, {
            name: 'name',
            attributeName: {
              localPart: 'name'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'Identifier',
        typeName: null,
        propertyInfos: [{
            name: 'value',
            type: 'value'
          }, {
            name: 'authority',
            attributeName: {
              localPart: 'authority'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'LegendURL',
        typeName: null,
        propertyInfos: [{
            name: 'format',
            elementName: 'Format'
          }, {
            name: 'onlineResource',
            elementName: 'OnlineResource',
            typeInfo: '.OnlineResource'
          }, {
            name: 'width',
            typeInfo: 'Integer',
            attributeName: {
              localPart: 'width'
            },
            type: 'attribute'
          }, {
            name: 'height',
            typeInfo: 'Integer',
            attributeName: {
              localPart: 'height'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'Keyword',
        typeName: null,
        propertyInfos: [{
            name: 'value',
            type: 'value'
          }, {
            name: 'vocabulary',
            attributeName: {
              localPart: 'vocabulary'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ContactPersonPrimary',
        typeName: null,
        propertyInfos: [{
            name: 'contactPerson',
            elementName: 'ContactPerson'
          }, {
            name: 'contactOrganization',
            elementName: 'ContactOrganization'
          }]
      }, {
        localName: 'Exception',
        typeName: null,
        propertyInfos: [{
            name: 'format',
            collection: true,
            elementName: 'Format'
          }]
      }],
    elementInfos: [{
        elementName: 'GetMap',
        typeInfo: '.OperationType'
      }, {
        elementName: 'WMS_Capabilities',
        typeInfo: '.WMSCapabilities'
      }, {
        elementName: 'Style',
        typeInfo: '.Style'
      }, {
        elementName: 'Address'
      }, {
        elementName: 'Capability',
        typeInfo: '.Capability'
      }, {
        elementName: 'StateOrProvince'
      }, {
        elementName: 'KeywordList',
        typeInfo: '.KeywordList'
      }, {
        elementName: 'AccessConstraints'
      }, {
        elementName: 'ContactVoiceTelephone'
      }, {
        elementName: 'ContactPersonPrimary',
        typeInfo: '.ContactPersonPrimary'
      }, {
        elementName: 'MetadataURL',
        typeInfo: '.MetadataURL'
      }, {
        elementName: 'GetFeatureInfo',
        typeInfo: '.OperationType'
      }, {
        elementName: 'MaxHeight',
        typeInfo: 'Integer'
      }, {
        elementName: 'StyleURL',
        typeInfo: '.StyleURL'
      }, {
        elementName: 'Attribution',
        typeInfo: '.Attribution'
      }, {
        elementName: 'Country'
      }, {
        elementName: 'Title'
      }, {
        elementName: 'LogoURL',
        typeInfo: '.LogoURL'
      }, {
        elementName: 'BoundingBox',
        typeInfo: '.BoundingBox'
      }, {
        elementName: 'Fees'
      }, {
        elementName: 'HTTP',
        typeInfo: '.HTTP'
      }, {
        elementName: 'CRS'
      }, {
        elementName: 'ContactPosition'
      }, {
        elementName: 'ContactAddress',
        typeInfo: '.ContactAddress'
      }, {
        elementName: 'FeatureListURL',
        typeInfo: '.FeatureListURL'
      }, {
        elementName: 'Service',
        typeInfo: '.Service'
      }, {
        elementName: 'Post',
        typeInfo: '.Post'
      }, {
        elementName: 'DataURL',
        typeInfo: '.DataURL'
      }, {
        elementName: 'DCPType',
        typeInfo: '.DCPType'
      }, {
        elementName: 'MaxScaleDenominator',
        typeInfo: 'Double'
      }, {
        elementName: 'Abstract'
      }, {
        elementName: 'EX_GeographicBoundingBox',
        typeInfo: '.EXGeographicBoundingBox'
      }, {
        elementName: 'Format'
      }, {
        elementName: 'LayerLimit',
        typeInfo: 'Integer'
      }, {
        elementName: 'Layer',
        typeInfo: '.Layer'
      }, {
        elementName: 'Keyword',
        typeInfo: '.Keyword'
      }, {
        elementName: 'ContactPerson'
      }, {
        elementName: 'GetCapabilities',
        typeInfo: '.OperationType'
      }, {
        elementName: 'StyleSheetURL',
        typeInfo: '.StyleSheetURL'
      }, {
        elementName: 'Name'
      }, {
        elementName: 'AddressType'
      }, {
        elementName: 'LegendURL',
        typeInfo: '.LegendURL'
      }, {
        elementName: '_ExtendedOperation',
        typeInfo: '.OperationType'
      }, {
        elementName: 'Dimension',
        typeInfo: '.Dimension'
      }, {
        elementName: 'ContactOrganization'
      }, {
        elementName: 'PostCode'
      }, {
        elementName: 'Get',
        typeInfo: '.Get'
      }, {
        elementName: 'Request',
        typeInfo: '.Request'
      }, {
        elementName: 'Exception',
        typeInfo: '.Exception'
      }, {
        elementName: '_ExtendedCapabilities',
        typeInfo: 'AnyType'
      }, {
        elementName: 'OnlineResource',
        typeInfo: '.OnlineResource'
      }, {
        elementName: 'ContactElectronicMailAddress'
      }, {
        elementName: 'ContactInformation',
        typeInfo: '.ContactInformation'
      }, {
        elementName: 'MinScaleDenominator',
        typeInfo: 'Double'
      }, {
        elementName: 'Identifier',
        typeInfo: '.Identifier'
      }, {
        elementName: 'ContactFacsimileTelephone'
      }, {
        elementName: 'MaxWidth',
        typeInfo: 'Integer'
      }, {
        elementName: 'AuthorityURL',
        typeInfo: '.AuthorityURL'
      }, {
        elementName: 'City'
      }]
  };
  return {
    WMS130: WMS130
  };
};
if (typeof define === 'function' && define.amd) {
  define([], WMS130_Module_Factory);
}
else {
  var WMS130_Module = WMS130_Module_Factory();
  if (typeof module !== 'undefined' && module.exports) {
    module.exports.WMS130 = WMS130_Module.WMS130;
  }
  else {
    var WMS130 = WMS130_Module.WMS130;
  }
}